/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#1a1c1b',
        'on-primary': '#ffffff',
        'primary-container': '#1a1c1b',
        'on-primary-container': '#838482',
        'primary-fixed': '#e2e3e0',
        'primary-fixed-dim': '#c6c7c5',
        'on-primary-fixed': '#1a1c1b',
        'on-primary-fixed-variant': '#454746',
        'secondary': '#605e55',
        'on-secondary': '#ffffff',
        'secondary-container': '#e6e2d6',
        'on-secondary-container': '#66645b',
        'secondary-fixed': '#e6e2d6',
        'secondary-fixed-dim': '#cac6bb',
        'on-secondary-fixed': '#1d1c15',
        'on-secondary-fixed-variant': '#48473e',
        'tertiary': '#000100',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#04201c',
        'on-tertiary-container': '#6e8a84',
        'tertiary-fixed': '#cbe9e2',
        'tertiary-fixed-dim': '#afcdc6',
        'on-tertiary-fixed': '#04201c',
        'on-tertiary-fixed-variant': '#314c47',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#fcfaed',
        'on-background': '#1b1c15',
        'surface': '#fcfaed',
        'on-surface': '#1b1c15',
        'surface-variant': '#e5e3d7',
        'on-surface-variant': '#444846',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f4e8',
        'surface-container': '#f0eee2',
        'surface-container-high': '#eae8dd',
        'surface-container-highest': '#e5e3d7',
        'surface-bright': '#fcfaed',
        'surface-dim': '#dcdacf',
        'surface-tint': '#5d5f5d',
        'outline': '#747876',
        'outline-variant': '#c4c7c4',
        'inverse-surface': '#303129',
        'inverse-on-surface': '#f3f1e5',
        'inverse-primary': '#c6c7c5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'h2': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'h1': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
        'container-max': '1120px',
      },
      maxWidth: {
        'container-max': '1120px',
      },
    },
  },
  plugins: [],
};
